#!/usr/bin/env python3
"""Photo-z and SED fitting with external codes (EAZY, CIGALE, Bagpipes, Prospector) through the adapters in sed_adapters/ (same adapters the AI-bridge profiles use).

    sedcodes.py --task photoz --code eazy --catalog TSV --work DIR [--engine native|external] [--python PY] [--command "prog args"] [--mag-columns MAG_F105W,...]
    sedcodes.py --task sed_fit --code cigale|bagpipes|prospector --catalog TSV --work DIR [--z-column COL] ...
    sedcodes.py --check [--code X] [--python PY]            availability report (JSON)
    sedcodes.py --write-profiles FILE                         ai_bridge profile file with local_command profiles for every code

Catalog columns MAG_<band> / MAGERR_<band> (band names of sed_adapters/filters.py, e.g. MAG_F160W) are the photometry.  stdout = TSV NUMBER + result columns.
"""
import argparse
import json
import os
import shlex
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, '..', '..'))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from ogfkit import tsvio, meta as ometa  # noqa: E402
from ai_bridge import records as brec  # noqa: E402
from sed_adapters import common, ADAPTERS, CODES  # noqa: E402

PHOTOZ_MAP = [('PHOTOZ', 'EZ_Z'), ('PHOTOZ_ERR', 'EZ_ZERR'), ('PHOTOZ_P16', 'EZ_Z16'), ('PHOTOZ_P50', 'EZ_Z50'), ('PHOTOZ_P84', 'EZ_Z84'), ('PHOTOZ_CHI2', 'EZ_CHI2')]
SED_MAP = [('LOG_MASS', 'SC_LOGM'), ('LOG_MASS_ERR', 'SC_LOGM_ERR'), ('LOG_AGE', 'SC_LOGAGE'), ('LOG_AGE_ERR', 'SC_LOGAGE_ERR'), ('LOG_Z', 'SC_LOGZ'), ('AV', 'SC_AV'),
           ('SFR', 'SC_SFR'), ('SED_CHI2', 'SC_CHI2')]
COLUMNS = {'photoz': [b for _, b in PHOTOZ_MAP] + ['EZ_NOTE'], 'sed_fit': [b for _, b in SED_MAP] + ['SC_NOTE']}


def build_params(a):
    p = {}
    for k in ('engine', 'python', 'eazy_data', 'filters_res', 'templates_file', 'point_estimate', 'z_column'):
        v = getattr(a, k)
        if v not in (None, ''):
            p[k] = v
    if a.command:
        p['command'] = shlex.split(a.command)
    for k in ('z_min', 'z_max', 'z_step', 'min_mag_err', 'default_mag_err', 'n_live', 'timeout'):
        v = getattr(a, k)
        if v is not None:
            p[k] = v
    if a.prior:
        p['prior'] = True
    if a.z_fixed is not None:
        p['z'] = a.z_fixed
    p['workdir'] = os.path.join(a.work, a.code)
    if a.params_json:
        with open(a.params_json) as f:
            p.update(json.load(f))
    return p


def profiles():
    """ai_bridge profiles (local_command) for every code: python -m sed_adapters.<code>_adapter reads the bridge JSON on stdin."""
    out = []
    for code, task in (('eazy', 'photoz'), ('cigale', 'sed_fit'), ('bagpipes', 'sed_fit'), ('prospector', 'sed_fit')):
        out.append({'name': 'sedcodes_' + code, 'template': False, 'enabled': False, 'description': 'Local %s through sed_adapters (set params / interpreter paths via --param)' % code,
                    'task': task, 'transport': 'local_command', 'command': ['python3', '-m', 'sed_adapters.%s_adapter' % code], 'env_passthrough': ['PYTHONPATH', 'EAZYCODE', 'SPS_HOME'],
                    'batch_size': 50, 'timeout_s': 3600,
                    '_note': 'Run with PYTHONPATH pointing at the OGFinder checkout. Parameters: --param python=/path/to/venv/python --param eazy_data=/path/eazy-photoz ... (docs/sed_codes.md)'})
    return {'schema': 1, '_README': 'Generated by plugins/sedcodes/sedcodes.py --write-profiles', 'services': out}


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('--task', choices=['photoz', 'sed_fit'], default='photoz')
    ap.add_argument('--code', default='eazy', choices=list(CODES))
    ap.add_argument('--catalog', default='')
    ap.add_argument('--work', default='.')
    ap.add_argument('--meta-out', default='')
    ap.add_argument('--mag-columns', default='')
    ap.add_argument('--max-objects', type=int, default=100000)
    ap.add_argument('--engine', default='native', choices=['native', 'external'])
    ap.add_argument('--python', default='')
    ap.add_argument('--command', default='')
    ap.add_argument('--eazy-data', dest='eazy_data', default='')
    ap.add_argument('--filters-res', dest='filters_res', default='')
    ap.add_argument('--templates-file', dest='templates_file', default='')
    ap.add_argument('--z-min', dest='z_min', type=float)
    ap.add_argument('--z-max', dest='z_max', type=float)
    ap.add_argument('--z-step', dest='z_step', type=float)
    ap.add_argument('--prior', action='store_true')
    ap.add_argument('--point-estimate', dest='point_estimate', default='peak', choices=['peak', 'ml'])
    ap.add_argument('--z-column', dest='z_column', default='Z_SPEC')
    ap.add_argument('--z', dest='z_fixed', type=float)
    ap.add_argument('--min-mag-err', dest='min_mag_err', type=float, default=0.02)
    ap.add_argument('--default-mag-err', dest='default_mag_err', type=float)
    ap.add_argument('--n-live', dest='n_live', type=int)
    ap.add_argument('--timeout', type=int)
    ap.add_argument('--params-json', default='')
    ap.add_argument('--check', action='store_true')
    ap.add_argument('--write-profiles', default='')
    a = ap.parse_args(argv)
    if a.write_profiles:
        with open(a.write_profiles, 'w') as f:
            json.dump(profiles(), f, indent=1)
        print(a.write_profiles)
        return 0
    mod = ADAPTERS[a.code]
    if a.check:
        print(json.dumps(common.clean(mod.check(build_params(a)) if hasattr(mod, 'check') else {'code': a.code}), indent=1))
        return 0
    if a.task not in mod.TASKS:
        sys.stderr.write('%s supports %s, not %s\n' % (a.code, '/'.join(mod.TASKS), a.task))
        return 2
    os.makedirs(a.work, exist_ok=True)
    header, rows = brec.read_catalog(a.catalog)
    toks = [c.strip() for c in a.mag_columns.replace(';', ',').split(',') if c.strip()]
    rename = {}                                   # 'MAG_AUTO:F160W' assigns a band name to a column that is not named MAG_<band>
    magc = []
    for t in toks:
        col, _, band = t.partition(':')
        magc.append(col)
        if band:
            rename[col[4:] if col.startswith('MAG_') else col] = band.strip()
    recs = brec.build_records(header, rows[:a.max_objects], mag_columns=magc or None)
    if rename:
        for r in recs:
            r['mags'] = {rename.get(k, k): v for k, v in r['mags'].items()}
            r['mag_errs'] = {rename.get(k, k): v for k, v in r['mag_errs'].items()}
    params = build_params(a)
    results, model = mod.process(recs, params, a.task)
    mp = PHOTOZ_MAP if a.task == 'photoz' else SED_MAP
    out = []
    nerr = 0
    note = 'EZ_NOTE' if a.task == 'photoz' else 'SC_NOTE'
    for r in results:
        d = {}
        if 'error' in r:
            nerr += 1
            d[note] = r['error']
        else:
            for k, name in mp:
                d[name] = r.get(k)
            if r.get('warning'):
                d[note] = r['warning']
        out.append((r['id'], d))
    sys.stderr.write('%s %s: %d objects, %d without result; model %s\n' % (a.code, a.task, len(out), nerr, model))
    with open(os.path.join(a.work, 'sedcodes_results.json'), 'w') as f:
        json.dump(common.clean({'code': a.code, 'task': a.task, 'model': model, 'params': {k: v for k, v in params.items() if k != 'workdir'}, 'results': results}), f)
    if a.meta_out:
        ometa.update(a.meta_out, 'sedcodes', {'code': a.code, 'task': a.task, 'model': model, 'n_ok': len(out) - nerr}, nrows=len(recs))
    tsvio.write_columns(COLUMNS[a.task], out)
    return 0


if __name__ == '__main__':
    sys.exit(main())
